apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: motionmesh
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${AWS_REGION}

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: motionmesh-secrets
  namespace: motionmesh
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: motionmesh-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgres://{{ .db_username }}:{{ .db_password | urlquery }}@${AURORA_ENDPOINT}/motionmesh?sslmode=require"
        DB_HOST: "${AURORA_HOST}"
        DB_PORT: "${AURORA_PORT}"
        DB_NAME: "motionmesh"
        DB_USER: "{{ .db_username }}"
        REDIS_URL: "redis://{{ .redis_host }}:{{ .redis_port }}"
        CLOUDFRONT_KEY_ID: "{{ .cf_key_id }}"
        CLOUDFRONT_PRIVATE_KEY: "{{ .cf_private_key }}"
  data:
    - secretKey: db_username
      remoteRef:
        key: ${DB_SECRET_ARN}
        property: username
    - secretKey: db_password
      remoteRef:
        key: ${DB_SECRET_ARN}
        property: password
    
    # Cloudfront key
    - secretKey: cf_key_id
      remoteRef:
        key: ${CLOUDFRONT_SECRET_ARN}
        property: key_id
    - secretKey: cf_private_key
      remoteRef:
        key: ${CLOUDFRONT_SECRET_ARN}
        property: private_key

    
    # Redis
    - secretKey: redis_host
      remoteRef:
        key: ${REDIS_SECRET_ARN}
        property: host
    - secretKey: redis_port
      remoteRef:
        key: ${REDIS_SECRET_ARN}
        property: port
